
public class ExceptionsVideoExamples {

	public static void main(String[] args) {
		exceptionOne();
		
		exceptionTwo();
		System.out.println("In main");
		
	}
	
	/**
	 * first exception example
	 */
	public static void exceptionOne() {
		int a, b = 6;
		 
		 try {
			 a = b / 0;
		 } catch(ArithmeticException ae) {
			 a = b;
			 System.out.println("Arithmetic Exception: " + ae.getMessage());
		 }
	}
	
	/**
	 * second exception example
	 */
	public static void exceptionTwo() {
		System.out.println("In exceptionTwo");
		exceptionTwoStackOne();
	}
	
	public static void exceptionTwoStackOne() {
		int num;
		System.out.println("In exceptionTwoStackOne");
		
		/**
		 * This line throws an exception. If the exception is not handled no code will be executed after this line; 
		 * this includes code written bellow the function callers that invoked this function: exceptionTwoStackOne() and exceptionTwo()
		 */
		num = 1 / 0;
	}

}
